version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 3000:3000
    volumes:
      - ./src:/srv/src
      - /node_modules
    depends_on:
      - database
    environment:
      - PORT=3000
      - DB_TYPE=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=nest-tasks
  database:
    image: postgres:latest
    restart: always
    volumes:
      - ../postgres-data_v2:/var/lib/postgresql/data_v2
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=nest-tasks
