version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 3000:3000
    volumes:
      - ./src:/srv/src
      - /node_modules
    environment:
      - PORT=3000
      - DB_TYPE=postgres
      - DB_HOST=127.0.0.1
      - DB_PORT=32768
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=nest-tasks
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - 32768:5432
    expose:
      - 32768
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=nest-tasks
